# This code follows the tutorial from the official IfcOpenShell library

import os

import ifcopenshell

path = os.path.join(os.path.dirname(__file__), 'Building-Architecture.ifc')
model = ifcopenshell.open(path)

# Check which schema is followed by the file
print(model.schema)

# Check piece of data (reads the row)
print(model.by_id(5))

# I can check if a global id is in the file
# In this case, IfcChimney is identified by the specified guid
print(model.by_guid('3dkFAzOGrAIuOzY_RdrdVv'))

# How many walls are in the file?
walls = model.by_type('IfcWall')
print(f"In this file there are {len(walls)} walls")

# We have an element, which class is it?
wall = model.by_type('IfcWall')[0]
print(wall.is_a())

# Test if the selected element is part of a certain class
print(wall.is_a('IfcWall')) # tautologic
print(wall.is_a('IfcElement')) # true, IfcElement is more general than IfcWall
print(wall.is_a('IfcWindow')) # false, IfcWindow cannot be also IfcWall
# class hierarchy inheritance, typical of EXPRESS schema, which is derived by UML
# ifc is a flat list of elements, relations are not expressed nesting

# Check the Step ID
print(wall.id())

# Attributes are ordered as a list
print("let's print the attributes accessing the list")
print(wall[0]) # GlobalId
print(wall[1]) # IfcOwnerHistory, who created the file, when with which software
print(wall[2]) # house - outer wall - house right front. Name attribute generated by the BIM software
print(wall[3]) # A solid outer wall, forming the right front side of the house - Description field
print(wall) # print all the list
print(len(wall))

# Access attribute by name
print(f"Attribute name is {wall.Name}")

# Access all attributes
print(wall.get_info())

# All properties and quantities
import ifcopenshell.util
import ifcopenshell.util.element

print (f"All properties and quantities are {ifcopenshell.util.element.get_psets(wall)}")

# Inverse attributes happen when another element is referencing our element, for example to define a relation
# A relation can be a void in the wall
print(f"Our wall is defined by {wall.IsDefinedBy}")
print(model.get_inverse(wall))

# And this is to check if our wall references other elements
print(model.traverse(wall))
# in a deeper leve
print(model.traverse(wall, max_levels=1))
# From this two commands you access also the geometry (try to check, you'll see many numbers)

# Modify data
# wall.Name = 'New wall name'

# Change GlobalId
# wall.GlobalId = ifcopenshell.guid.new()

# Save in a new file
# model.write('....ifc')

# Generate a new .ifc
# ifc = ifcopenshell.file(schema='IFC4')

# Create new elements, like a new wall
# new_wall = model.createIfcWall() # returns a list with our new wall

# Alternatively
# model.create_entity('IfcWall')
# model.create_entity('IfcWall', ifcopenshell.guid.name())
# model.create_entity('IfcWall', GlobalId = ifcopenshell.guid.new(), Name = 'Wall Name')

""" data = {
    'GlobalId' : ifcopenshell.guid.new(),
    'Name' : 'Wall Name'
}

model.create_entity('IfcWall', **data)
"""

# Add a reference
# wall = model.createIfcWall()
# wall.OwnerHistory = model.createIfcOwnerHistory()

# Add an element from another IFC
"""wall = model.by_type('IfcWall')[0]
new_model = ifcopenshell.file()
new_model.add(wall)"""

# Delete an object
# model.remove(wall)


"""
Il file IFC (.ifc) è strutturalmente una lista piatta di entità numerate (#N=ENTITÀ(...)), non un formato nidificato come JSON o XML.
Le relazioni tra le righe (es. un muro che referenzia la sua collocazione spaziale o la sua geometria) sono espresse tramite riferimenti numerici (#245, #1...)
e sono interpretabili solo grazie allo schema EXPRESS esterno, che definisce quali entità esistono e come si relazionano — in questo IFC è concettualmente più
vicino al dump di un database relazionale (dati piatti + schema esterno) che a un documento auto-descrittivo come JSON, dove invece è proprio il nesting
sintattico a costituire la relazione.

Dal file Building-Architecture.ifc si nota bene come una certa riga ne referenzia un'altra

#311=IFCSURFACESTYLERENDERING(#312,0.,$,$,$,$,$,$,.NOTDEFINED.);
#312=IFCCOLOURRGB($,1.,1.,1.);

Quindi sappiamo che IFCSURFACESTYLERENDERING referenzia IFCCOLOURRGB. Se controlliamo di cosa si tratta diventa ancora più chiaro
IFCSURFACESTYLERENDERING = holds the properties for visualization related to a particular surface style. Three lighting models are supported.
IFCCOLOURRGB =  A colour rgb as a subtype of colour specifications is defined by three colour component values for red, green, and blue in the RGB colour model
Per IFCCOLOURRGB il $ indica Name nullo/non definito. R=1, G=1 e B=1 sono normalizzati : il muro è completamente bianco
"""